# kuri Theme Config @ version 1.0.0
# website: https://kuri.ink | cl@kuri.ink

# Yourself / 个人信息
nickname: 216的博客日记
motto: 记录20岁的以后
logo: 
github: https://github.com/amanmanlai-byte
background:
  - https://i.pinimg.com/1200x/af/91/1b/af911b8119ee0cc0d44c031be361a802.jpg
iconfont: /css/iconfont.css

# SEO / 搜索引擎优化
fav: /images/fav.png

# Sidebar / 侧边栏
sidebar:
  A1: # 类别名称
    B1: # 项目名称
      - https://example.com/ # 超链接
      - example # MDUI 鼠标悬停工具提示

sidebar_color: 
  A1: # 类别名称
    - near_me # 图标
    - mdui-text-color-blue # 图标颜色

# Header / 页眉信息
chizaobook: true # true / false 在页眉显示摛藻好句功能

# Social / 社交按钮
social:
  X:
    - https://x.com/zengwanlin_
    - '@zengwanlin_'
    - /images/x-logo.png
  GitHub:
    - https://github.com/amanmanlai-byte
    - https://github.com/amanmanlai-byte
    - https://i.pinimg.com/736x/5b/e1/0f/5be10f1ea3625480288bfd567b68bba8.jpg

# Footer / 页脚信息
## copyright / 版权
author: 216
## remark / 备注
remark: ''
## Regist / 备案
regist: ''

# tools / 工具
analysis: 
  platform: 51.la
  id: 
  cd: 
aplayer: 
  enable: false
  platform: 
  type: 
  id: 
  fixed: true